@startuml
instrumento <|-- guitarra
instrumento <|-- saxo
instrumento <|-- tiple

musico *-- instrumento
banda *-- musico

instrumento:afinar()
instrumento:tocar()
musico:instrumento
musico:afinar_instrumento()
musico:tocar_instrumento()

@enduml

